version: "2.2"

services:
  challenge:
    container_name: challenge
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 4200:4200
    networks:
      - overlay
networks:
  overlay: